#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.2 on Fri Jan 20 18:48:56 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class OperatingMode(wx.Panel):
    def __init__(self, parent,):
        # begin wxGlade: OperatingMode.__init__
        wx.Panel.__init__(self, parent=parent)
        
        self.operatingMode = "Safety"
        
        self.label_Instructions = wx.StaticText(self, wx.ID_ANY, _("Help text goes here"))
        self.button_Safety = wx.Button(self, wx.ID_ANY, _("Safety"))
        self.button_Test = wx.Button(self, wx.ID_ANY, _("Test"))
        self.button_Arm = wx.Button(self, wx.ID_ANY, _("Arm"))

        self.__set_properties()
        self.__do_layout()

        #self.Bind(wx.EVT_BUTTON, self.OnButton_Mode, self.button_Safety)
        #self.Bind(wx.EVT_BUTTON, self.OnButton_Mode, self.button_Test)
        #self.Bind(wx.EVT_BUTTON, self.OnButton_Mode, self.button_Arm)
        # end wxGlade

    def __set_properties(self):
        self.button_Safety.SetBackgroundColour(wx.NamedColour('GREEN'))
        self.button_Test.SetBackgroundColour(wx.NamedColour('BLUE'))
        self.button_Arm.SetBackgroundColour(wx.NamedColour('RED'))

    def __do_layout(self):
        # begin wxGlade: OperatingMode.__do_layout
        sizer_OperatingMode = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, _("Operating Mode")), wx.VERTICAL)
        sizer_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_OperatingMode.Add(self.label_Instructions, 1, wx.EXPAND, 0)
        sizer_buttons.Add(self.button_Safety, 1, wx.EXPAND, 0)
        sizer_buttons.Add(self.button_Test, 1, wx.EXPAND, 0)
        sizer_buttons.Add(self.button_Arm, 1, wx.EXPAND, 0)
        sizer_OperatingMode.Add(sizer_buttons, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_OperatingMode)
        sizer_OperatingMode.Fit(self)
        self.Layout()
        # end wxGlade


