#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.2 on Sat Jan 21 10:44:29 2017
#

import wx
import wx.grid

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Sequencer(wx.Panel):
    def __init__(self, parent):
        # begin wxGlade: Sequencer.__init__
        wx.Panel.__init__(self, parent=parent)
        self.button_Sequencer_Start = wx.Button(self, wx.ID_ANY, _("Start"))
        self.button_Sequencer_Stop = wx.Button(self, wx.ID_ANY, _("Stop"))
        self.button_Sequencer_Reset = wx.Button(self, wx.ID_ANY, _("Reset"))
        self.button_Sequencer_Load = wx.Button(self, wx.ID_ANY, _("Load"))
        self.button_Sequencer_Save = wx.Button(self, wx.ID_ANY, _("Save"))
        self.grid_Sequencer_Edit = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Sequencer.__set_properties
        self.grid_Sequencer_Edit.CreateGrid(128, 2)
        self.grid_Sequencer_Edit.SetColLabelValue(0, _("Channel"))
        self.grid_Sequencer_Edit.SetColLabelValue(1, _("Time"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Sequencer.__do_layout
        sizer_Outer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, _("Sequencer")), wx.HORIZONTAL)
        sizer_editor = wx.BoxSizer(wx.VERTICAL)
        sizer_Sequencer_LoadButtons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_buttons = wx.BoxSizer(wx.VERTICAL)
        sizer_buttons.Add(self.button_Sequencer_Start, 1, wx.EXPAND, 0)
        sizer_buttons.Add(self.button_Sequencer_Stop, 1, wx.EXPAND, 0)
        sizer_buttons.Add(self.button_Sequencer_Reset, 1, wx.EXPAND, 0)
        sizer_Outer.Add(sizer_buttons, 1, wx.EXPAND, 0)
        sizer_Sequencer_LoadButtons.Add(self.button_Sequencer_Load, 0, 0, 0)
        sizer_Sequencer_LoadButtons.Add(self.button_Sequencer_Save, 0, 0, 0)
        sizer_editor.Add(sizer_Sequencer_LoadButtons, 0, 0, 0)
        sizer_editor.Add(self.grid_Sequencer_Edit, 1, wx.EXPAND, 0)
        sizer_Outer.Add(sizer_editor, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_Outer)
        sizer_Outer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Sequencer
