#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.2 on Sat Jan 21 16:56:48 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade
import SequencerProgram
# begin wxGlade: extracode
# end wxGlade


class Sequencer(wx.Panel):
    def __init__(self, parent):
        # begin wxGlade: Sequencer.__init__
        wx.Panel.__init__(self, parent=parent)
        
        self.masterTimerDecoder = []
        
        self.button_Sequencer_BankA = wx.Button(self, wx.ID_ANY, _("A"))
        self.button_Sequencer_BankB = wx.Button(self, wx.ID_ANY, _("B"))
        self.button_Sequencer_BankC = wx.Button(self, wx.ID_ANY, _("C"))
        self.button_Sequencer_BankD = wx.Button(self, wx.ID_ANY, _("D"))
        
        self.defaultColor = self.button_Sequencer_BankD.GetBackgroundColour()
        
        self.Panel_SequencerA = SequencerProgram.SequencerProgram(self, name = "A")
        self.Panel_SequencerB = SequencerProgram.SequencerProgram(self, name = "B")
        self.Panel_SequencerC = SequencerProgram.SequencerProgram(self, name = "C")
        self.Panel_SequencerD = SequencerProgram.SequencerProgram(self, name = "D")
        
        self.panelList = [self.Panel_SequencerA,
                          self.Panel_SequencerB,
                          self.Panel_SequencerC,
                          self.Panel_SequencerD]
        
        self.buttonList = [self.button_Sequencer_BankA,
                           self.button_Sequencer_BankB,
                           self.button_Sequencer_BankC,
                           self.button_Sequencer_BankD]
        
        for panel in self.panelList:
            panel.Hide()
        self.panelList[0].Show()

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        self.Bind(wx.EVT_BUTTON, self.OnButton_Bank, self.button_Sequencer_BankA)
        self.Bind(wx.EVT_BUTTON, self.OnButton_Bank, self.button_Sequencer_BankB)
        self.Bind(wx.EVT_BUTTON, self.OnButton_Bank, self.button_Sequencer_BankC)
        self.Bind(wx.EVT_BUTTON, self.OnButton_Bank, self.button_Sequencer_BankD)
        

    def __set_properties(self):
        # begin wxGlade: Sequencer.__set_properties
        for button in self.buttonList:
            button.SetBackgroundColour(self.defaultColor)
        self.button_Sequencer_BankA.SetBackgroundColour(wx.NamedColour('YELLOW'))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Sequencer.__do_layout
        sizer_Outer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, _("Sequencer")), wx.HORIZONTAL)
        sizer_BankSelect = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, _("Bank Select")), wx.VERTICAL)
        sizer_BankSelect.Add(self.button_Sequencer_BankA, 1, wx.EXPAND, 0)
        sizer_BankSelect.Add(self.button_Sequencer_BankB, 1, wx.EXPAND, 0)
        sizer_BankSelect.Add(self.button_Sequencer_BankC, 1, wx.EXPAND, 0)
        sizer_BankSelect.Add(self.button_Sequencer_BankD, 1, wx.EXPAND, 0)
        sizer_Outer.Add(sizer_BankSelect, 1, wx.EXPAND, 0)

        
        
        for panel in self.panelList:
            sizer_Outer.Add(panel, 6, wx.EXPAND, 0)
        
        self.SetSizer(sizer_Outer)
        sizer_Outer.Fit(self)
        self.Layout()
        # end wxGlade
    
    def OnButton_Bank(self, event):
        label = event.GetEventObject().GetLabel()
        for panel in self.panelList:
            panel.Hide()
        for button in self.buttonList:
            button.SetBackgroundColour(self.defaultColor)
        if label == "A":
            self.panelList[0].Show()
            self.button_Sequencer_BankA.SetBackgroundColour(wx.NamedColour('YELLOW'))
            print "OnButton_Bank: Showing Panel A"
        elif label == "B":
            self.panelList[1].Show()
            self.button_Sequencer_BankB.SetBackgroundColour(wx.NamedColour('YELLOW'))
            print "OnButton_Bank: Showing Panel B"
        elif label == "C":
            self.panelList[2].Show()
            self.button_Sequencer_BankC.SetBackgroundColour(wx.NamedColour('YELLOW'))
            print "OnButton_Bank: Showing Panel C"
        elif label == "D":
            self.panelList[3].Show()
            self.button_Sequencer_BankD.SetBackgroundColour(wx.NamedColour('YELLOW'))
            print "OnButton_Bank: Showing Panel D"
        self.Layout()
# end of class Sequencer
